wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708011129.780475
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.10.13
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 10
fc_layer_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: adam
