wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707975606.617966
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 19
      - 23
      4: 3.10.13
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
lr:
  desc: null
  value: 0.01
