wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708010191.572634
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.13
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 40
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 1
fc_layer_size:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.011269024679185991
optimizer:
  desc: null
  value: adam
