wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707971423.842363
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
